# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

betanew_lasso_cpp <- function(xx, xy, beta, M, y, Lambda1, Lambda2, iter, tol) {
    .Call('LassoNet_betanew_lasso_cpp', PACKAGE = 'LassoNet', xx, xy, beta, M, y, Lambda1, Lambda2, iter, tol)
}

